spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
security.trust-forwarded-headers=true
server.forward-headers-strategy=framework
wallet.topup.demo-enabled=false
wallet.kafka.replication-factor=${KAFKA_REPLICATION_FACTOR:1}
server.error.include-message=never
server.error.include-stacktrace=never
springdoc.swagger-ui.enabled=${SWAGGER_ENABLED:true}
springdoc.api-docs.enabled=${SWAGGER_ENABLED:true}

razorpay.key-id=${RAZORPAY_KEY_ID:}
razorpay.key-secret=${RAZORPAY_KEY_SECRET:}
razorpay.webhook-secret=${RAZORPAY_WEBHOOK_SECRET:}

razorpay.api-base-url=${RAZORPAY_API_BASE_URL:https://api.razorpay.com/v1}
