package com.example.phoneWallet.enums;

public enum AuditAction {
    USER_SIGNUP, USER_SIGNUP_FAILED, USER_LOGIN, USER_LOGIN_FAILED, USER_ROLE_CHANGED,
    WALLET_CREATED, WALLET_BALANCE_VIEWED,
    TOPUP_INITIATED, TOPUP_COMPLETED, TOPUP_FAILED,
    LOAD_MONEY_SUCCESS, LOAD_MONEY_FAILED,
    TRANSFER_SUCCESS, TRANSFER_FAILED,
    MERCHANT_PAYMENT_SUCCESS, MERCHANT_PAYMENT_FAILED,
    REFUND_SUCCESS, REFUND_FAILED,
    WALLET_FROZEN, WALLET_UNFROZEN, WALLET_BLACKLISTED, WALLET_UNBLACKLISTED,
    REVERSAL_SUCCESS, REVERSAL_FAILED
}
