package com.example.phoneWallet.enums;

public enum ErrorCode {
    WALLET_NOT_FOUND, DUPLICATE_WALLET, WALLET_FROZEN, INSUFFICIENT_BALANCE, INVALID_AMOUNT,
    TRANSACTION_NOT_FOUND, TRANSACTION_NOT_COMPLETED, INVALID_TRANSACTION, LEDGER_VALIDATION_FAILED, AMOUNT_MISMATCH,
    USERNAME_ALREADY_EXISTS, USER_NOT_FOUND, INVALID_CREDENTIALS,
    TRANSACTION_BLOCKED, VALIDATION_ERROR, ACCESS_DENIED, UNAUTHORIZED, DATABASE_CONSTRAINT_ERROR, INTERNAL_SERVER_ERROR,
    REFRESH_TOKEN_NOT_FOUND, REFRESH_TOKEN_EXPIRED, REFRESH_TOKEN_REVOKED, RATE_LIMIT_EXCEEDED,
    DEPENDENCY_UNAVAILABLE, INVALID_TOP_UP, IDEMPOTENCY_IN_PROGRESS
}
